---
apiVersion: carto.run/v1alpha1
kind: Workload
metadata:
  name: ml-backstage-plugin
  labels:
    apps.tanzu.vmware.com/workload-type: web
    app.kubernetes.io/part-of: ml-backstage-plugin
  annotations:
    autoscaling.knative.dev/minScale: "1"
spec:
  params:
    - name: clusterBuilder
      value: full
  env:
    - name: MLFLOW_TRACKING_URI
      value: http://mlflow.tanzumlai.com
  source:
    git:
      url: https://github.com/agapebondservant/ml-backstage-plugin-accelerator.git
      ref:
        branch: main